CREATE TABLE "cliente" (
  "id_cliente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "email" varchar(120) UNIQUE,
  "telefono" varchar(20),
  "direccion" varchar(200)
);

CREATE TABLE "cuenta" (
  "id_cuenta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" int,
  "numero_cuenta" varchar(20) UNIQUE,
  "tipo" varchar(50),
  "saldo" numeric(12,2),
  "fecha_apertura" date
);

CREATE TABLE "tipo_transaccion" (
  "id_tipo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50),
  "descripcion" varchar(200)
);

CREATE TABLE "transaccion" (
  "id_transaccion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cuenta" int,
  "id_tipo" int,
  "fecha" timestamp,
  "monto" numeric(12,2),
  "descripcion" varchar(200)
);

ALTER TABLE "cuenta" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id_cliente");

ALTER TABLE "transaccion" ADD FOREIGN KEY ("id_cuenta") REFERENCES "cuenta" ("id_cuenta");

ALTER TABLE "transaccion" ADD FOREIGN KEY ("id_tipo") REFERENCES "tipo_transaccion" ("id_tipo");
