CREATE TABLE "cliente" (
  "id_cliente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "email" varchar(120) UNIQUE,
  "telefono" varchar(20),
  "direccion" varchar(200)
);

CREATE TABLE "sucursal" (
  "id_sucursal" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "ciudad" varchar(50),
  "direccion" varchar(200)
);

CREATE TABLE "tarifa" (
  "id_tarifa" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "peso_min" numeric(6,2),
  "peso_max" numeric(6,2),
  "costo" numeric(12,2)
);

CREATE TABLE "encomienda" (
  "id_encomienda" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" int,
  "id_sucursal_origen" int,
  "id_sucursal_destino" int,
  "id_tarifa" int,
  "peso" numeric(6,2),
  "fecha_envio" date,
  "fecha_entrega" date,
  "estado" varchar(50)
);

CREATE TABLE "historial_estado" (
  "id_historial" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_encomienda" int,
  "estado" varchar(50),
  "fecha" timestamp
);

ALTER TABLE "encomienda" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id_cliente");

ALTER TABLE "encomienda" ADD FOREIGN KEY ("id_sucursal_origen") REFERENCES "sucursal" ("id_sucursal");

ALTER TABLE "encomienda" ADD FOREIGN KEY ("id_sucursal_destino") REFERENCES "sucursal" ("id_sucursal");

ALTER TABLE "encomienda" ADD FOREIGN KEY ("id_tarifa") REFERENCES "tarifa" ("id_tarifa");

ALTER TABLE "historial_estado" ADD FOREIGN KEY ("id_encomienda") REFERENCES "encomienda" ("id_encomienda");
