CREATE TABLE "cliente" (
  "id_cliente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "email" varchar(120) UNIQUE,
  "telefono" varchar(20),
  "direccion" varchar(200)
);

CREATE TABLE "categoria" (
  "id_categoria" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "descripcion" varchar(200)
);

CREATE TABLE "producto" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_categoria" int,
  "nombre" varchar(100),
  "descripcion" varchar(200),
  "precio" numeric(12,2),
  "stock" int
);

CREATE TABLE "pedido" (
  "id_cliente" int,
  "id_pedido" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" timestamp,
  "total" numeric(12,2),
  "estado" varchar(50)
);

CREATE TABLE "detalle_pedido" (
  "id_producto" int,
  "id_pedido" int,
  "cantidad" int,
  "precio_unitario" numeric(12,2),
  PRIMARY KEY ("id_producto", "id_pedido")
);

CREATE TABLE "pago" (
  "id_pago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pedido" int,
  "fecha" timestamp,
  "monto" numeric(12,2),
  "metodo" varchar(50)
);

ALTER TABLE "producto" ADD FOREIGN KEY ("id_categoria") REFERENCES "categoria" ("id_categoria");

ALTER TABLE "pedido" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id_cliente");

ALTER TABLE "detalle_pedido" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id_producto");

ALTER TABLE "detalle_pedido" ADD FOREIGN KEY ("id_pedido") REFERENCES "pedido" ("id_pedido");

ALTER TABLE "pago" ADD FOREIGN KEY ("id_pedido") REFERENCES "pedido" ("id_pedido");
